-- 租户内置角色默认权限回灌

BEGIN;

WITH
    defaults ("roleCode", "permissionCode") AS (
        VALUES
            -- TENANT_OWNER：等价于 ALL_TENANT_PERMISSION_CODES（25 项）
            (
                'TENANT_OWNER',
                'analytics.read'
            ),
            ('TENANT_OWNER', 'orders.read'),
            (
                'TENANT_OWNER',
                'orders.manage'
            ),
            (
                'TENANT_OWNER',
                'orders.import.manage'
            ),
            (
                'TENANT_OWNER',
                'orders.print.manage'
            ),
            (
                'TENANT_OWNER',
                'orders.reminder.create'
            ),
            (
                'TENANT_OWNER',
                'templates.read'
            ),
            (
                'TENANT_OWNER',
                'templates.manage'
            ),
            (
                'TENANT_OWNER',
                'credit.receipt.create'
            ),
            (
                'TENANT_OWNER',
                'payments.read'
            ),
            (
                'TENANT_OWNER',
                'payments.offline_payment_verify.create'
            ),
            (
                'TENANT_OWNER',
                'finance.read'
            ),
            (
                'TENANT_OWNER',
                'finance.export'
            ),
            (
                'TENANT_OWNER',
                'printing.config.read'
            ),
            (
                'TENANT_OWNER',
                'printing.config.update'
            ),
            (
                'TENANT_OWNER',
                'settings.general.manage'
            ),
            (
                'TENANT_OWNER',
                'settings.users.manage'
            ),
            (
                'TENANT_OWNER',
                'settings.roles.manage'
            ),
            (
                'TENANT_OWNER',
                'settings.audit_logs.read'
            ),
            (
                'TENANT_OWNER',
                'settings.payment_configs.read'
            ),
            (
                'TENANT_OWNER',
                'settings.payment_configs.manage'
            ),
            (
                'TENANT_OWNER',
                'tenant.profile.read'
            ),
            (
                'TENANT_OWNER',
                'tenant.certification.manage'
            ),
            (
                'TENANT_OWNER',
                'notifications.read'
            ),
            (
                'TENANT_OWNER',
                'notifications.manage'
            ),
            -- TENANT_FINANCE（13 项）
            (
                'TENANT_FINANCE',
                'analytics.read'
            ),
            (
                'TENANT_FINANCE',
                'orders.read'
            ),
            (
                'TENANT_FINANCE',
                'orders.reminder.create'
            ),
            (
                'TENANT_FINANCE',
                'templates.read'
            ),
            (
                'TENANT_FINANCE',
                'credit.receipt.create'
            ),
            (
                'TENANT_FINANCE',
                'payments.read'
            ),
            (
                'TENANT_FINANCE',
                'payments.offline_payment_verify.create'
            ),
            (
                'TENANT_FINANCE',
                'finance.read'
            ),
            (
                'TENANT_FINANCE',
                'finance.export'
            ),
            (
                'TENANT_FINANCE',
                'settings.payment_configs.read'
            ),
            (
                'TENANT_FINANCE',
                'tenant.profile.read'
            ),
            (
                'TENANT_FINANCE',
                'notifications.read'
            ),
            (
                'TENANT_FINANCE',
                'notifications.manage'
            ),
            -- TENANT_OPERATOR（10 项）
            (
                'TENANT_OPERATOR',
                'orders.read'
            ),
            (
                'TENANT_OPERATOR',
                'orders.manage'
            ),
            (
                'TENANT_OPERATOR',
                'orders.import.manage'
            ),
            (
                'TENANT_OPERATOR',
                'orders.print.manage'
            ),
            (
                'TENANT_OPERATOR',
                'templates.read'
            ),
            (
                'TENANT_OPERATOR',
                'templates.manage'
            ),
            (
                'TENANT_OPERATOR',
                'printing.config.read'
            ),
            (
                'TENANT_OPERATOR',
                'tenant.profile.read'
            ),
            (
                'TENANT_OPERATOR',
                'notifications.read'
            ),
            (
                'TENANT_OPERATOR',
                'notifications.manage'
            ),
            -- TENANT_VIEWER（5 项）
            (
                'TENANT_VIEWER',
                'analytics.read'
            ),
            (
                'TENANT_VIEWER',
                'orders.read'
            ),
            (
                'TENANT_VIEWER',
                'templates.read'
            ),
            (
                'TENANT_VIEWER',
                'tenant.profile.read'
            ),
            (
                'TENANT_VIEWER',
                'notifications.read'
            )
    )
INSERT INTO
    "tenant_role_permissions" ("roleId", "permissionCode")
SELECT tr.id, d."permissionCode"
FROM "tenant_roles" tr
    JOIN defaults d ON d."roleCode" = tr.code
WHERE
    tr."deletedAt" IS NULL
ON CONFLICT ("roleId", "permissionCode") DO NOTHING;

COMMIT;
